### ISSUE TITLE
Mic Allocation Todo list

### ISSUE THREAD

**Issue by mstratford** [dreamteamprod/DigiScript#443]
While speed running mic allocations:
- [ ] Opening the "New Mic" Popup will clear itself if the addition of a previous Mic is still processing.
- [ ] Add option for mass "Add N mics".
- [ ] Add "Select All/None" to each mic allocation row
- [ ] Default to Mic 1 during mic editing? No point defaulting to N/A.
- [ ] Make Mic Edit vs Mic View more obvious than just the text in the button.
